config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'projects#index'

  resources :projects do
    resources :hours, only: [:create, :edit, :update, :destroy]
    resources :invoices
    get '/invoices/:id/pdf', to: 'invoices#pdf'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charge.rb
class Charge < ApplicationRecord
  validates :hours, presence: true, numericality: { greater_than: 0 }
  validates :rate, presence: true, numericality: { greater_than: 0 }
  validates :description, presence: true
  belongs_to :invoice
end

app/models/hour.rb
class Hour < ApplicationRecord
  validates :hours, presence: true, numericality: { greater_than: 0 }
  validates :date, presence: true
  belongs_to :project
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :project
  has_many :charges
  accepts_nested_attributes_for :charges

  def subtotal
    subtotal = 0
    self.charges.each do |c|
        subtotal += c.hours * c.rate
    end
    subtotal
  end

  def total
    self.subtotal - self.discount
  end

end

app/models/project.rb
class Project < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true
    has_many :hours
    has_many :invoices
    belongs_to :user

    def total_hours_worked
        total_hours = 0
        self.hours.each do |h|
            total_hours += h.hours
        end
        total_hours
    end

    def total_earned
        total_earned = 0
        self.invoices
            .where('created_at > ?', 30.days.ago)
            .each do |h|
                total_earned += h.total
        end
        total_earned
    end

    def total_hours_invoiced
        total_invoiced = 0
        self.invoices.each do |h|
            total_invoiced += h.hours
        end
        total_invoiced
    end

    def ref_no
        # TODO: Change X to real iterated letter value
        self.created_at.strftime('%y%m?')
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :projects

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hours_controller.rb
class HoursController < ApplicationController
    before_action :authenticate_user!
    before_action :set_project, only: [:create, :edit, :update, :destroy]
    before_action :set_hour, only: [:edit, :update, :destroy]

    def create
      @hour = @project.hours.build(hour_params)
      if @hour.save
        redirect_to @project, notice: 'Hours successfully created.'
      else
        redirect_to @project, notice: 'There was a problem.'
      end
    end

    def edit
    end

    def update
      if @hour.update(hour_params)
        redirect_to @project, notice: 'Hours successfully amended.'
      else
        redirect_to @project, notice: 'There was a problem.'
      end
    end

    def destroy
      @hour.destroy
      redirect_to @project, notice: 'Hours successfully removed.'
    end

    private

    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_hour
      @hour = current_user.projects.hours.find(params[:id])
    end

    def hour_params
        params.require(:hour).permit(:description, :hours, :date)
    end

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
    before_action :authenticate_user!, except: [:show, ;pdf]
    before_action :set_project

    def pdf
        render pdf: "invoice"
    end

    def new
        @invoice = @project.invoices.new
        @invoice.charges.new
    end

    def create
        @invoice = @project.invoices.build(invoice_params)
        if @invoice.save
          redirect_to @project, notice: 'Invoice successfully created.'
        else
          redirect_to @project, notice: 'There was a problem.'
        end
    end

    def show
        @invoice = @project.invoices.find(params[:id])
    end

    private

    def set_project
        @project = current_user.projects.find(params[:project_id])
    end

    def invoice_params
        params.require(:invoice).permit(:discount, charges_attributes: [:description, :notes, :rate, :hours])
    end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = current_user.projects
      # .where(user_id: current_user.id)
  end

  def show
    @hours = @project.hours.order("created_at DESC").limit(6)
    @invoices = @project.invoices

    @hour = @project.hours.build
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
      if @project.save
        redirect_to @project, notice: 'Project successfully created.'
      else
        render :new
      end
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path, notice: 'Project successfully removed.'
  end

  private

  def set_project
    @project = current_user.projects.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :email, :address)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hours_helper.rb
module HoursHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/hours/_add-hours-form.html.erb
<%= form_for [@project, @hour] do |form| %>
    <div class="dialog__body">
        <h3 class="section-title dialog__title">Add hours</h3>
        <div class="two-column-grid">
            <div class="form-field">
                <%= form.label(:hours, "Hours worked", {class: "form-label"}) %>
                <%= form.number_field(:hours, {class: "form-input", min: "0.5", step: "0.5", required: "true"}) %>
            </div>
            <div class="form-field">
                <%= form.label(:date, "On date", {class: "form-label"}) %>
                <%= form.date_field(:date, {class: "form-input form-input--date", required: "true"}) %>
            </div>
        </div>
        <div class="form-field form-field--no-bottom-margin">
            <%= form.label(:description, "Describe the work", {class: "form-label"}) %>
            <p class="form-optional">Optional</p>
            <%= form.text_area(:description, {class: "form-input"}) %>
        </div>
    </div>
    <footer class="dialog__footer">
        <%= form.submit("Add hours", {class: "button button--filled"}) %>
    </footer>    
<% end %>

app/views/hours/_recent-hours.html.erb
<section class="recent hours">
    <h2 class="section-title">Recent hours</h2>
    <div class="recent-hours__controls">
        <button class="button button--filled" id="show-add-hours">Add hours</button>
    </div>
    <div class="two-column-grid recent-hours__list">
    <% @hours.each do |hour| %>
        <li class="recent-hours__hours panel">
            <h3><%= hour.id %>. <%= number_with_precision(hour.hours, precision: 1, significant: true, strip_insignificant_zeros: true) %> hours</h3>
            <p><%= hour.description %></p>
            <%= link_to("Amend", edit_project_hour_path(@project, hour), {class: "inline-interaction"}) %>
        </li>
    <% end %>
</section>

<dialog id="add-hours-dialog" class="dialog">
    <button class="dialog__close" id="close-add-hours-dialog"><%= image_tag('cross.svg') %></button>
    <%= render 'hours/add-hours-form' %>
</dialog>

app/views/hours/edit.html.erb
<div class="three-column-grid">

    <main class="span-two-thirds">
        <h1 class="page-title">Editing hours</h1>
        <div class="panel">

            <%= form_with(model: [@project, @hour]) do |form| %>

                <div class="form-field">
                    <%= form.label(:hours, "Hours worked", {class: "form-label"}) %>
                    <%= form.number_field(:hours, {class: "form-input", min: "0.5", step: "0.5", required: "true"}) %>
                </div>
                <div class="form-field">
                    <%= form.label(:date, "On date", {class: "form-label"}) %>
                    <%= form.date_field(:date, {class: "form-input form-input--date", required: "true"}) %>
                </div>
                <div class="form-field">
                    <%= form.label(:description, "Describe the work", {class: "form-label"}) %>
                    <p class="form-optional">Optional</p>
                    <%= form.text_area(:description, {class: "form-input"}) %>
                </div>
                <%= form.submit("Update", {class: "button button--filled"}) %>
            <% end %>

            <%= link_to("Remove", project_hour_path(@project, @hour), method: :delete, data: {confirm: "Are you sure?"}) %>

        </div>
    </main>

</div>

app/views/invoices/_recent-invoices.html.erb
<section class="recent invoices">
    <h2 class="section-title">Recent invoices</h2>
    <div class="recent-invoices__controls">
        <%= link_to "Create invoice", new_project_invoice_path(@project), {class: "button button--filled"} %>
    </div>
    <div class="two-column-grid recent-invoices__list">

    <% @invoices.each do |invoice| %>
        <li class="recent-invoices__invoices panel">
            <h3>ID: <%= invoice.id %></h3>
            <p>Subtotal: £<%= invoice.subtotal %></p>
            <p>Discount: £<%= invoice.discount %></p>
            <p>Total: £<%= invoice.total %></p>
            <%= link_to "Review invoice", project_invoice_path(@project, invoice) %>
        </li>
    <% end %>
    
    </div>
</section>

app/views/invoices/new.html.erb
<h1 class="page-title">Create a new invoice</h1>
<div class="panel">

    <%= form_for [@project, @invoice] do |f| %>

        <div class="form-field">
            <%= f.label :discount, {class: "form-label"} %><br/>
            <%= f.number_field :discount, {class: "form-input  form-input--limited-width", min: 0, step: 0.5} %><br/>
        </div>

        <h3 class="panel__title">Charges</h3>

        <table>
            <thead>
                <tr>
                    <th>Description</th>
                    <th>Notes</th>
                    <th>Hours worked</th>
                    <th>Hourly rate</th>
                </tr>
            </thead>
            <tbody id="charges-table-body">
                <%= f.fields_for :charges do |ff| %>
                    <tr>
                        <td>
                            <%= ff.text_field :description, {class: "form-input", required: "true"} %>
                        </td>
                        <td>
                            <%= ff.text_area :notes, {class: "form-input"} %>
                        </td>
                        <td>
                            <%= ff.number_field :hours, {class: "form-input", required: "true", min: 0, step: 0.5} %>
                        </td>
                        <td>
                            <%= ff.number_field :rate, {class: "form-input", required: "true", min: 0, step: 0.5} %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>

        <button class="button button--outline" id="append-charge-row">Add another charge</button>


        <%= f.submit "Create & finish", {class: "button button--filled"} %>

    <% end %>

</div>

app/views/invoices/pdf.html.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
    <%= wicked_pdf_javascript_include_tag "number_pages" %>
  </head>
  <body onload='number_pages'>
    <div id="header">
      <%= wicked_pdf_image_tag 'mysite.jpg' %>
    </div>
    <div id="content">
      <%= yield %>
      <p>wub wub</p>
    </div>
  </body>
</html>

app/views/invoices/show.html.erb
<h3>ID: <%= @invoice.id %></h3>
<p>Subtotal: £<%= @invoice.subtotal %></p>
<p>Discount: £<%= @invoice.discount %></p>
<p>Total: £<%= @invoice.total %></p>
<p>created <%= time_ago_in_words(@invoice.created_at) %> ago</p>


<% @invoice.charges.each do |charge| %>
    <li>
        <%= charge.description %>, <%= charge.hours %>, <%= charge.rate %>
    </li>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="site-footer">
    <div class="container">
        <p class="site-footer__copyright">Built by <a href="#">Jaye Hackett</a></p>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="site-header">
    <div class="container">
        <%= link_to(root_path, {class: "site-header__brand"}) do %>
            <%= image_tag("logo.svg", alt: "Sellsword", class: "site-header__logo") %>
            <h1 class="site-header__title">Sellsword</h1>
        <% end %>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Sellsword</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path("favicon.png") %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container main-content">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>

  <%# Error summary %>
  <% if project.errors.any? %>
    <div class="alert alert--error">
      <h4 class="alert__title"><%= pluralize(project.errors.count, "error") %> prevented this project from being saved</h4>
      <ul class="alert__message">
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-field form-field--with-bottom-margin">
    <%= form.label(:name, "Client name", {class: "form-label"}) %>
    <%= form.text_field(:name, {class: "form-input form-input--limited-width", required: true}) %>
  </div>

  <div class="form-field form-field--with-bottom-margin">
    <%= form.label(:email, "Billing email", {class: "form-label"}) %>
    <%= form.email_field(:email, {class: "form-input form-input--limited-width", required: true}) %>
    <p class="form-hint">Invoices will be sent here</p>
  </div>

  <div class="form-field form-field--with-bottom-margin">
    <%= form.label(:address, "Other contact details", {class: "form-label form-label--optional"}) %>
    <p class="form-optional">Optional</p>
    <%= form.text_area(:address, {class: "form-input", rows: "4"}) %>
    <p class="form-hint">Will be printed on invoices</p>
  </div>

  <%= form.submit("Create & finish", {class: "button button--filled"}) %>

<% end %>

app/views/projects/_project-details-dialog.html.erb
<dialog id="project-details-dialog" class="dialog">
    <button class="dialog__close" id="project-details-dialog"><%= image_tag('cross.svg') %></button>
    <div class="dialog__body">
        <h3 class="section-title dialog__title">Project details</h3>
        <div class="project-details">
            <aside class="project-details__detail">
                <h5 class="project-details__title">Billing email</h5>
                <p><%= @project.email %></p>
            </aside>
            <% if @project.address.length > 0 %>
                <aside class="project-details__detail">
                    <h5 class="project-details__title">Other contact details</h5>
                    <p><%= @project.address %></p>
                </aside>
            <% end %>
            <aside class="project-details__detail">
                <h5 class="project-details__title">Reference number</h5>
                <p><%= @project.ref_no %></p>
            </aside>

            <aside class="project-details__detail">
                <h5 class="project-details__title">Created</h5>
                <p><%= time_ago_in_words(@project.created_at) %> ago</p>
            </aside>
        </div>
    </div>
    <footer class="dialog__footer">
        <%= link_to 'Edit details', edit_project_path(@project), {class: "button button--outline"} %>
        <%# <%= link_to 'Destroy', @project, method: :delete, data: { confirm: 'Are you sure?' }, class: "inline-interaction" %>
    </footer>
</dialog>

app/views/projects/edit.html.erb
<div class="three-column-grid">
    <main class="span-two-thirds">
        <h1 class="page-title">Editing <%= @project.name %></h1>
        <div class="panel">
            <h3 class="panel__title">About the client</h3>
            <%= render 'form', project: @project %>

            <%= link_to 'Show', @project, {class: "inline-interaction"} %>
            <%= link_to 'Back', projects_path, {class: "inline-interaction"} %>
            
            <%= link_to 'Remove', project_path, method: :delete, data: {confirm: "Are you sure?"} %>

        </div>
    </main>
</div>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<section class="recent-projects">
  <h2 class="section-title recent-projects__title">Recent projects</h2>
  <div class="recent-projects__controls">
    <%= link_to 'New project', new_project_path, {class: "button button--filled"} %>
  </div>
  <div class="recent-projects__list">
    <% @projects.each do |project| %>
      <%= link_to(project, {class: "recent-projects__project panel"}) do %>
        <aside class="recent-projects__info">
          <h3 class="recent-projects__name"><%= project.name %></h3>
          <p class="recent-projects__published">Created <%= time_ago_in_words(project.created_at) %> ago</p>
        </aside> 
        <blockquote class="statistic">
          <q class="statistic__stat"><%= project.total_hours_worked %></q>
          <cite class="statistic__caption">Hours worked so far</cite>
        </blockquote>
        <blockquote class="statistic">
          <q class="statistic__stat">£<%= project.total_earned %></q>
          <cite class="statistic__caption">Earned so far</cite>
        </blockquote>
      <% end %>
    <% end %>
  </div>
</section>

app/views/projects/new.html.erb
<div class="three-column-grid">
    <main class="span-two-thirds">
        <h1 class="page-title">Create a new project</h1>
        <div class="panel">
            <h3 class="panel__title">About the client</h3>
            <%= render 'form', project: @project %>
        </div>
    </main>
</div>

app/views/projects/show.html.erb
<p class="page-intro">Project</p>
<h1 class="page-title page-title--with-lede"><%= @project.name %></h1>
<button class="inline-interaction page-details" id="show-project-details">See client details</button>

<% if notice %>
    <p id="notice" class="alert"><%= notice %></p>
<% end %>

<%= render 'project-details-dialog'%>

<%= render 'hours/recent-hours'%>

<%= render 'invoices/recent-invoices'%>